### ISSUE TITLE
function doubt

### ISSUE THREAD

**Issue by shiuanyue** [emipa606/SomeThingsFloat#4]
Could you explain the [Forbid when leaving stockpile] function for me?
no noticeable behavior after turning off the feature

**Comment by emipa606** [comment]
The tooltip should explain it but if turned on, any thing that floats out of a stockpile where it is allowed will be forbidden.
If turned off nothing will change when it floats out of the stockpile.

**Comment by shiuanyue** [comment]
So if I set up a storage area for dead bodies on the river
After the corpse is washed away by the river, the colonists will ignore it??

**Comment by emipa606** [comment]
Yes, with the option on they will float away and marked as forbidden

**Comment by shiuanyue** [comment]
OK
