### ISSUE TITLE
Random error today

### ISSUE THREAD

**Issue by PandaMcBoomBoom** [emipa606/SomeThingsFloat#9]
It's been playing and working fine, I did add that everyone can have possessions mod but I don't see any mention of it in the error. I tried to do the ctrl + F12 thing but it always throws me an error (I have REALLY slow internet, idk if that affects it tho) But it constant throws errors, and bogs down my frames every like 5 to 10ish minutes with this error
But here's the error I copied over. I am also newish to Github, I don't understand it too well so hopefully this is the right spot for this. 
[the error.txt](https://github.com/emipa606/SomeThingsFloat/files/11035226/the.error.txt)

**Comment by emipa606** [comment]
Can you look into what pawn is in the water and from what mod its from? Apparently somd pawn in the water have no capacity worker for breathing

**Comment by PandaMcBoomBoom** [comment]
None of my pawns are in the water at all, I just checked it and they were all asleep in beds and I turned on dev mode and the error just goes on forever. I do use this androids don't breath mod (https://steamcommunity.com/sharedfiles/filedetails/?id=2926403329&searchtext=android+breathing) For Rimnauts 2 (Universum). Could that be the issue?

**Comment by emipa606** [comment]
Okay, made a change in how breathing is calculated. 
Hopefully it fixes it.
